.phony: clean all

all:
	make -C 00_hello_avr
	make -C 01_led_blink
	make -C 02_digital_in
	make -C 03_timer
	make -C 04_external_interrupt
	make -C 05_uart

clean:
	make -C 00_hello_avr clean
	make -C 01_led_blink clean
	make -C 02_digital_in clean
	make -C 03_timer clean
	make -C 04_external_interrupt clean
	make -C 05_uart clean
